spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/agentcart
spring.datasource.username=root
spring.datasource.password=Soniya@2005

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

razorpay.key.id=rzp_test_TWdAiNBNQ4fNAQ
razorpay.key.secret=vxUuD7QzCI2iutGmph2CQ2py